version: "3.8"
services: 
    app:
        build: 
            context: .
        volumes: 
            - .:/kitten-app
        ports:
            - 3000:3000
        image: app:react
        container_name: Kittenapp_container
        command: yarn start